-- Disable arrow keys for now
vim.keymap.set('i', '<Up>', '<Nop>')
vim.keymap.set('i', '<Down>', '<Nop>')
vim.keymap.set('i', '<Right>', '<Nop>')
vim.keymap.set('i', '<Left>', '<Nop>')
vim.keymap.set('n', '<Up>', '<Nop>')
vim.keymap.set('n', '<Down>', '<Nop>')
vim.keymap.set('n', '<Right>', '<Nop>')
vim.keymap.set('n', '<Left>', '<Nop>')
vim.keymap.set('x', '<Up>', '<Nop>')
vim.keymap.set('x', '<Down>', '<Nop>')
vim.keymap.set('x', '<Right>', '<Nop>')
vim.keymap.set('x', '<Left>', '<Nop>')
