general.import = ["/Users/stephanvs/dotfiles/alacritty/catppuccin-mocha.toml"]
general.live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u004b"
key = "k"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u004a"
key = "j"
mods = "Command"

[window]
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 5
y = 5
