general.import = ['C:\Users\steph\dotfiles/alacritty/catppuccin-mocha.yml']
general.live_config_reload = true
general.working_directory = "E:/Code/"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[terminal.shell]
args = ["-NoLogo"]
program = "pwsh.exe"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 0
y = 0
