import = ['C:\Users\steph\dotfiles/alacritty/catppuccin-mocha.yml']
live_config_reload = true
working_directory = "E:/Code/"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[shell]
args = ["-NoLogo"]
program = "pwsh.exe"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 0
y = 0
