#!/bin/zsh

# lin: ~/.config/qutebrowser/config.py
# mac: ~/.qutebrowser/config.py
# win: %APPDATA%/qutebrowser/config/config.py

case "$OSTYPE" in
    darwin*)
        ln -sf  $DOTFILES/qutebrowser/config.py $HOME/.qutebrowser/config.py
        git clone https://github.com/catppuccin/qutebrowser.git $HOME/.qutebrowser/catppuccin
        ;;
    linux*)
        mkdir -p $HOME/.config/qutebrowser
        ln -f --symbolic $DOTFILES/qutebrowser/config.py $HOME/.config/qutebrowser/config.py

        git clone https://github.com/catppuccin/qutebrowser.git ~/.config/qutebrowser/catppuccin
        ;;
    *)
        echo "OS not supported"
        ;;
esac

