# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
format = "$symbol "
success_symbol = "[➜](bold green)"
error_symbol   = "[✖](bold red)"

[directory]
truncation_length = 8
truncation_symbol = "…/"
style = "bold yellow"

[username]
show_always = true
format = "[$user]($style) in "
style_user = "bold blue"
style_root = "bold red"

[hostname]
ssh_only = false
trim_at = ""
format = "[$hostname]($style) in "