set-environment -gF TMUX_PLUGIN_MANAGER_PATH '#{HOME}/.tmux/plugins/'

if 'test ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm"' {
  run 'mkdir -p "${TMUX_PLUGIN_MANAGER_PATH}"'
  run 'git clone https://github.com/tmux-plugins/tpm "${TMUX_PLUGIN_MANAGER_PATH}/tpm"'
  run '${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins'
}

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sunaku/tmux-navigate'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'fabioluciano/tmux-powerkit'

source-file "$DOTFILES/tmux/common.conf"

# ==============================
# TPM PLUGIN MANAGEMENT BINDINGS
# ============================================================

# Switch to TPM bindings mode: prefix + g
bind-key -N 'Switch to plugin bindings' -T prefix 'g' {
  switch-client -T tpm-bindings
  display-message -d 1000 '#{E:log_info} in tpm-bindings mode'
}

bind-key -N 'Reload tmux configuration' -T tpm-bindings  'r' reload-config

bind-key -N 'TPM - Install plugins' -T tpm-bindings  'i' {
  display-message -d 1000 '#{E:log_info} Installing plugins... '
  run-shell '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/bindings/install_plugins'
}

bind-key -N 'TPM - Update plugins' -T tpm-bindings  'u' {
  display-message -d 1000 '#{E:log_info} Updating plugins... '
  run-shell '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/bindings/update_plugins'
}

bind-key -N 'TPM - Clean plugins' -T tpm-bindings  'x' {
  display-message -d 1000 '#{E:log_info} Cleaning plugins... '
  run-shell '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/bindings/clean_plugins'
}

# Delete unneeded key bindings
unbind-key -a -T copy-mode

# Delete old TPM key bindings (now using prefix + g)
unbind-key -T prefix I
unbind-key -T prefix U

# ============================================================
# Initialize TPM (MUST BE AT THE END)
# ============================================================
run -b '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm'
